caesarHQ/textSQL

- client/src/App.js
Server can be spammed by empty queries
commented out unused res variable
> Prevent empty queries, commented unused variable

- README.md
- api/README.md
- api/app/api/utils.py
- api/app/config.py
- client/README.md
- client/package.json
- client/src/App.js
- Fix the `St. Petersburg` issue by text replacement.
- Separated the dev and prod environments and made configs in separate files.
- Updates the READMEs.
> St. Petersbug fix, Separated environments, updated READMEs

- client/src/App.js
> fix double fetch xoxo

- README.md
> potential limitations/biases disclaimer(?)

- client/src/App.js
- client/src/components/examples.js
- client/yarn.lock
- Replaced the loosely comparison operator with the strict comparison operator.
-  Removed unused imports.
- Replaced the anchor tag in the `examples.js` file with the `<p>` element.
> remove warnings and use best practices

- client/src/components/examples.js
- client/yarn.lock
Changes the cursor style to pointer when one of the example cards is hovered on.
> refactor: change cursor style to pointer

- api/app/config.py
use environment variable to set open ai key
> getenv("OPENAI_KEY")

- api/app/api/utils.py
I’m not sure if this entire approach is actually secure, and maybe will look it over a little better when I have time, but in the meantime just adding a couple more keywords that should definitely be blocked
> Add CREATE,ALTER,GRANT to blacklist

- client/src/App.js
Updates the URL to '/' instead of the previous query after home click reload
> update url on home click

- client/src/App.js
- client/src/css/App.css
You can now hit the 'x' to clear your current query
> add x to clear

- client/src/App.js
https://github.com/caesarHQ/textSQL/issues/37
> auto fetch when loading a link

- api/app/api/utils.py
We don't want GPT to TRUNCATE our TABLES
> prevent TRUNCATE

- api/discordbot/bot.py
- api/discordbot/responses.py
- api/requirements.txt
> add discord bot with tabular responses

- client/src/App.js
- client/src/Discord.js
- client/src/components/table.js
- client/yarn.lock
- Added formatting of numbers, percentages, title in the data
- Added code for button to contribute data which can be used later once the form is ready
> Added formatting of numbers and implemented button for contribute

- client/src/components/table.js
- Fix typecasting with numbers (convert them to string to format them)
- Disable formatting if there's a decimal point there
> Fix typecasting with numbers and disable formatting when its a decimal

- client/src/App.js
- client/src/Discord.js
- client/src/components/examples.js
- client/src/components/table.js
- client/tailwind.config.js
Adding dark mode
Edited minor css in components to consolidate most dark mode style changes on App.js root div
> Add dark mode

- client/package-lock.json
- client/package.json
- client/pnpm-lock.yaml
- client/src/App.js
- client/src/components/table.js
- client/yarn.lock
Also adjusted table and search with dark mode styles
> Add sql highlighting

- client/package-lock.json
- client/src/App.js
- client/src/components/disclaimer.js
- client/yarn.lock
I added a disclaimer component and also integrated the dark and light mode into it.
> added the disclaimer component

- client/.eslintignore
- client/.eslintrc.json
- client/package-lock.json
- client/package.json
- client/yarn.lock
- Add basic eslint config
- Add lint command `npm run lint` or `npm run lint src/App.js`
Will eventually need a hook to enforce eslint before committing
> Add basic eslint config

- client/src/Discord.js
- client/yarn.lock
We want to hide the icons on mobile so it looks prettier.  Please check the vercel link for example of how it looks
> hide icons on mobile

- client/src/App.js
Use search icon instead of button to reduce clutter
> use search button icon

- client/src/Toast.js
- client/src/index.js
- set pool size and timeout
- pool
- Update utils.py
- fix config stuff
- change api endpoint
- get parallelization ready
- -1 -> k
- fix clean sql
- add discord bot with tabular responses
- add eslint
- fix column order
- update requirements.txt
- add failed query handling
- add param
- Added formatting of numbers and implemented button for contribute which can be used later
- Update utils.py
- Configure db connection to be read-only
- format
- add githb actions for prettier as well as eslint
- set up env var for environment
- ENV = getenv("ENVIRONMENT") or "unknown"
- add dev db
- correct population column names
- run fixers instead
- if 'table_names' not passed in body, use middle step to infer relevant tables
- add summarize first
- add summarize first
- first rephrase the query
- …
> eslint fixes

- client/package-lock.json
- client/pnpm-lock.yaml
- client/src/App.js
- client/src/Discord.js
- client/src/components/examples.js
- client/src/components/table.js
- client/tailwind.config.js
- client/yarn.lock
> update dark mode theme to match mapbox

- client/src/App.js
> update sql background

- api/app/api/routes.py
- api/app/api/utils/sql_gen/tests/test_txt_to_sql.py
- api/app/api/utils/sql_gen/text_to_sql.py
- api/requirements.txt
> add simple test suite for BE

- client/src/components/vizSelector.js
- client/src/plotly-ui-config.js
> plotly dark mode and viz selector styles

- client/src/App.js
SELECT zip_code, 
(white_population / NULLIF(total_population, 0)) * 100 AS white_percentage,
(black_population / NULLIF(total_population, 0)) * 100 AS black_percentage,
(native_american_population / NULLIF(total_population, 0)) * 100 AS native_american_percentage,
(asian_population / NULLIF(total_population, 0)) * 100 AS asian_percentage,
(two_or_more_population / NULLIF(total_population, 0)) * 100 AS two_or_more_percentage,
(hispanic_population / NULLIF(total_population, 0)) * 100 AS hispanic_percentage
FROM acs_census_data
WHERE city = 'San Francisco'
ORDER BY (white_population + black_population + native_american_population + asian_population + two_or_more_population + hispanic_population) DESC
LIMIT 1
> copy sql to clipboard

- client/src/utils.js
cc: @alex-sun-kuo re: https://github.com/caesarHQ/textSQL/issues/99
> make query keyword string replacement word-bound and case insensitive

- client/src/App.js
> fix sentry error for undefined query

- client/censusGPT/package-lock.json
- client/censusGPT/pnpm-lock.yaml
- client/censusGPT/src/App.js
- client/censusGPT/yarn.lock
> integrate /explain_sql

- api/app/config.py
Hard to understand error on first install when DB env not found
> display right away if db not found and exit

- api/scripts/setup.sh
Figured it said to use 3.10 so why not
> make the venv3.10
